{% set name = "FiPy" %}
{% set version = "3.3" %}
{% set sha256 = "bd6731d99fb3003f3a1ef402f520385d4d21afc5de45fc1c6b7b5da7d45de858" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/usnistgov/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - future
    - python
    - pip
    - numpy
    - scipy
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - gmsh <4.0   # [not (win and (py2k or x86))]
    - pysparse    # [not py3k]
    - pytrilinos  # [not win and not py3k]
    - mpi4py      # [not win and not py3k]
    - matplotlib <3.0  # [py2k]
    - matplotlib >3.0  # [py3k]
    - mayavi
#    - weave <=0.16     # [not py3k]

test:
  imports:
    - fipy

about:
  home: http://www.ctcms.nist.gov/fipy
  license: NIST public domain
  license_file: LICENSE.rst
  summary: A finite volume partial differential equation solver using Python
  description: |
    FiPy is an object oriented, partial differential equation (PDE) solver,
    written in Python, based on a standard finite volume (FV) approach. The
    framework has been developed in the Materials Science and Engineering
    Division (MSED) and Center for Theoretical and Computational Materials
    Science (CTCMS), in the Material Measurement Laboratory (MML) at the
    National Institute of Standards and Technology (NIST). The solution of
    coupled sets of PDEs is ubiquitous to the numerical simulation of
    science problems. 
    |
    Numerous PDE solvers exist, using a variety of languages and numerical
    approaches. Many are proprietary, expensive and difficult to customize.
    As a result, scientists spend considerable resources repeatedly
    developing limited tools for specific problems. Our approach, combining
    the FV method and Python, provides a tool that is extensible, powerful
    and freely available. A significant advantage to Python is the existing
    suite of tools for array calculations, sparse matrices and data
    rendering.
    |
    The FiPy framework includes terms for transient diffusion, convection
    and standard sources, enabling the solution of arbitrary combinations
    of coupled elliptic, hyperbolic and parabolic PDEs. Currently
    implemented models include phase field treatments of polycrystalline,
    dendritic, and electrochemical phase transformations as well as a level
    set treatment of the electrodeposition process.
  doc_url: http://www.ctcms.nist.gov/fipy
  dev_url: https://github.com/usnistgov/fipy

extra:
  recipe-maintainers:
    - guyer
