travis:
  secure:
    BINSTAR_TOKEN: YDKwsfK0AwDEiSPSchnqiHnrPvqHG7mwOIcejME9V5FQDFB10P7TmSYALemJio5r3FC/eanP00BC8Jz8fpaWrUuiuNRoLMtugk0mmxT2nM36edZAJjzUBH+cjsCe49RO7itTCTa3ET2d7gPGQepM1AQCQfqIkMfB0TXuDxxKOFaHZxmS+mYu93GuZYxDioRjAx1bamD/w5sJ4Xwv/HyC3AT9f4jw+/zZ7+JpYx8C5SiwQS05g6XW4ZlPejD4rMOVodlyE0cR8kwFdxCm6JHV0ttr3xYpols/F2L0t+fFO86LpO0dqMyok7KfODNuAi3995umwenExawSMl0dV0ZvY74CFLc8Yf9PfDpLijbXiKiloeTVTHPBL96Bdl1h5Y02t6VVZqNECdiL3R5/d/kJnBe9Y1sies5dF1+ljcEw6sdwkaUVDWe6JghPm1BOUbi0EvLbpmmKHooqzKlASye0ABxM1LqaV9OG1F8WLvwOSfYIGyWfJgKd5nBJ7+3WT4pMz9KF4lwZK2E1cQ6/0fgLHU7NKr8nxFuFeDH6W5JOWAPguaGKOaEBNubuBmCSX6ALFqvCd9ALWCizx7rHFaqs6YaxlOjbfgOnDvxQSJjChpV+RN4PfxP7C2UNc5xsgOzqHnGLG8MIUZvdRYZvjcWJPoiY9b2oj7GmMZOeVUHM62A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
