travis:
  secure:
    BINSTAR_TOKEN: QduQ0g7VM0nICEphwRHhO+G8omXt25C0lcFVoEM3Cigob4+Ql7UXeWkH8I+/R8pAnSVe/zqU3coI0A0DKrC7E0chKilk6AAepJJyiBlS1kM7pN3joOLKtyUPYXEO4bJzZczmrAYev7vg7cQ+bTsr7DMGQFbsdMENjn85lDmq431TGqFjh6lZpEc7gzdBeKLzBf8j3BtYzk5nCRFtkUVMmUObpr9L67FRm3BOvRMwGL4eovLh7IzybgF+WDUdeQH1Z25qv/vu3uUfveJb4ZmZNXoX9TYMSoJf/wZlIy43gZzb+L4kyGPY0ip+4TW0fOtgmpt7QJDlzjzOIUt6KfnMy5n0xl91NiDnl/wawmR4rFPUVS9yfn7xfwZLdo7WIMyq7azfV5yUJ1KmgrAYYHMom+mP2mOA9gRrZxw4Uh+p5yCIBzwJMGTEDBUpwAbUtZgXYm22Fbs6qlsixjL0rgjDbQyE9h17EdkSbg2hVY+X3Jkl+uQ8aqJehLPyjULFy6rcPwNUxIx7KZixFFOqijzIW9zh8Mq1Y2nYkN39xvS/aSMvRLWRmCr8Uk0JQMW7rNFPj7rpOakmuw8Yt9XPZMkseFb4YbmRxWVVJnZsb8L71u3fFTQEb/AuieKBwWCiZZ2QX+6GntnwhRvd4LEv22cyaG5Llj++ZI1DYoo0CVyV860=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
